# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default=b'', max_length=30)),
                ('model', models.CharField(default=b'', max_length=30)),
                ('number', models.CharField(default=b'', max_length=20)),
                ('max_weight', models.IntegerField(null=True)),
                ('max_volume', models.IntegerField(null=True)),
                ('is_broken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('car', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auto_base.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_city', models.CharField(default=b'', max_length=30)),
                ('end_city', models.CharField(default=b'', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trip',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auto_base.Trip'),
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auto_base.Driver'),
        ),
    ]
